### ISSUE TITLE
convert getBooks into an async call

### ISSUE THREAD

**Issue by bzhou93** [minhphan156/book-store#19]
Include authors and genres in response. Show stock photo if cover does not exist for book.

If time permits:
Currently, displaying the books could crash in the middle and prevent any later books from being displayed.  Need to turn it into an async call so that even if something goes wrong for one book, we can load the rest

**Comment by gauravdesai** [comment]
getBooks should also retrieve author and genre info for books and send them to the frontend with all other information

**Comment by bzhou93** [comment]
getBooks should also provide a stock photo if the cover is null.

**Comment by bzhou93** [comment]
The branch for this issue was mistakenly named "issue18".  The branch "issue19" is now associated with issue 18, and branch "issue18" is now associated with this issue.

**Comment by bzhou93** [comment]
May bundle fixes to upload API call in this branch - will see.
